---
title           : "My preregistration for AsPredicted.org"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Jannick Akkermans
    affiliation : 1

affiliation:
  - id          : 1
    institution : Utrecht University

output: prereg::aspredicted_prereg
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->


## Existing data
<!-- Have any data been collected for this study already? Note: You must answer 'No' to submit this pre-registration at AsPredicted.org. -->

**Yes**, some data was provided at the start of the project

## Hypothesis
<!-- What's the main question being asked or hypothesis being tested in this study? Providing a short name for each hypothesis (e.g. H1, H2, etc.) will later allow you to easily relate your hypotheses to statistical tests in your analysis plan. -->

> The main question is 'How well can highly urbanized regions versus lowly urbanized regions be classified?'. The corresponding hypothesis (H1) is that an accuracy higher than 50% will be achieved. This accuracy of 50% would be achieved if a classifier assigned one of the two classes to each case.

## Dependent variable
<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> A variable indicating whether a region has high urbanization (more than 80% of the region is urbanized) or low urbanization (less than 20% of the region is urbanized).


## Conditions
<!-- How many and which conditions will participants be assigned to? -->

> None


## Analyses
<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> The hypothesis will be tested by means of two classification algorithms. The first algorithm is logistic regression in which the urbanization will be predicted using the remaining variables as predictors. The second classification algorithm is a random forest. This algorithm will also predict urbanization using the remaing variables as predictors. The random forest will contain 2000 decision trees. 

> For each classification algorithm, the performance is based on the achieved accuracy, i.e. the proportion of correctly classified cases.

> For each classification algorithm, the data will be split into a training set and a test set, with a division of 75/25 respectively. Therefore, 75% of the data will be assigned to the training set and 25% to the test set. The algorithm will subsequently be trained using the training data and then applied to the test set.

> Before the analyses, the data are scaled so that the scales are approximately equal.


## More analyses
<!-- Any secondary analyses? -->

> None


## Sample Size
<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> Data from 1337 regions has been collected by the Global Data Lab. At the start of the project, data from 217 regions has been provided. Therefore, the sample size is 217.


## Other
<!-- Anything else you would like to pre-register? (e.g., data exclusions, variables collected for exploratory purposes, unusual analyses planned?) -->

> Categorical variables other than the urbanization variable will be removed from the dataset. The random forest classifier has trouble with such predictors, which is why they are removed from the dataset before the analyses are conducted.

# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
